ShopOnline/Areas/Admin/Controllers/AdminPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Models;
using X.PagedList;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "1")]
    public class AdminPagesController : Controller
    {
        private readonly WebBanhangDbContext _context;

        public AdminPagesController(WebBanhangDbContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminPages
        public IActionResult Index(int? page, string searchString)
        {
            var pages = _context.Pages.AsQueryable();

            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;

            if (!string.IsNullOrEmpty(searchString))
            {
                pages = pages.Where(a => a.PageName.Contains(searchString));
            }

            pages = pages.OrderByDescending(c => c.CreatedDate); 

            var pagedPage = new PagedList<Page>(pages, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentFilter = searchString;

            return View(pagedPage);
        }


        // GET: Admin/AdminPages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages
                .FirstOrDefaultAsync(m => m.PageId == id);
            if (page == null)
            {
                return NotFound();
            }

            return View(page);
        }

        // GET: Admin/AdminPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Page page, IFormFile Avatar)
        {
            if (ModelState.IsValid)
            {
                if (Avatar != null && Avatar.Length > 0)
                {
                    var fileName = Path.GetFileNameWithoutExtension(Avatar.FileName);
                    var extension = Path.GetExtension(Avatar.FileName);
                    string newFileName = $"{fileName}_{DateTime.Now.Ticks}{extension}";
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images/Pages", newFileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        Avatar.CopyToAsync(stream);
                    }

                    page.Thumb = newFileName;

                }
                page.Alias = Helper.Utilities.GenerateAlias(page.PageName);
                page.CreatedDate = DateTime.Now;
                _context.Add(page);
                _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var page = await _context.Pages.FindAsync(id);
            if (page == null)
            {
                return NotFound();
            }
            return View(page);
        }

        // POST: Admin/AdminPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Page page, IFormFile Avatar)
        {
            if (id != page.PageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Avatar != null && Avatar.Length > 0)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(Avatar.FileName);
                        var extension = Path.GetExtension(Avatar.FileName);
                        string newFileName = $"{fileName}_{DateTime.Now.Ticks}{extension}";
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images/Pages", newFileName);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            Avatar.CopyToAsync(stream);
                        }

                        page.Thumb = newFileName;

                    }
                    page.Alias = Helper.Utilities.GenerateAlias(page.PageName);
                    _context.Update(page);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PageExists(page.PageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(page);
        }

        // GET: Admin/AdminPages/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var page = await _context.Pages
        //        .FirstOrDefaultAsync(m => m.PageId == id);
        //    if (page == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(page);
        //}

        // POST: Admin/AdminPages/Delete/5
        [HttpPost, ActionName("Delete")]

        public IActionResult Delete(int id)
        {
            var page =  _context.Pages.Find(id);
            if (!string.IsNullOrEmpty(page.Thumb))
            {
                var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images/Pages", page.Thumb);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }
            if (page != null)
            {
                _context.Pages.Remove(page);
            }
          
            _context.SaveChanges();
            return Json(new { success = true, message = "Xóa thành công" });
        }

        private bool PageExists(int id)
        {
            return _context.Pages.Any(e => e.PageId == id);
        }
    }
}

ShopOnline/Areas/Admin/Views/AdminPages/Create.cshtml
@model ShopOnline.Models.Page

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h1>Tạo mới</h1>


<hr />
<div class="container mt-4">
    <div class="card shadow-sm rounded">
        <div class="card-header bg-info text-white">
            <h5 class="mb-0">Thêm mới Page</h5>
        </div>
        <div class="card-body">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PageName" class="control-label"></label>
                <input asp-for="PageName" class="form-control" />
                <span asp-validation-for="PageName" class="text-danger"></span>
            </div>
             <div class="form-group">
                 <label for="exampleInputEmail1">Nội dung</label>
                 @Html.TextAreaFor(x => x.Contents, new { @class = "form-control", @placeholder = "Nội dung", @id = "txtDetail" })
                 @Html.ValidationMessageFor(x => x.Contents, null, new { @class = "text-danger" })
             </div>

            <div class="form-group mb-3">
                    <label asp-for="Thumb" class="form-label">Ảnh đại diện</label>
                    <input type="file" name="Avatar" class="form-control" accept="image/*" />
                    <img id="previewAvatar" class="img-thumbnail mt-2" style="display:none;" width="100" />
            </div> 
               


            <div class="form-group">
                <label asp-for="Publish" class="control-label">Công khai</label>
                @Html.DropDownListFor(model => model.Publish,
                         new List<SelectListItem>
                {
                new SelectListItem { Text = "Hoạt động", Value = "true" },
                new SelectListItem { Text = "Bị khóa", Value = "false" }
                },
                         htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="Publish" class="text-danger small"></span>
            </div>
        
          
               
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
          
          
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input asp-for="Ordering" class="form-control" />
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>


<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>
@section script {
    <script>
        document.querySelector('input[type="file"][name="Avatar"]').addEventListener('change', function (e) {
            const [file] = e.target.files;
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    const preview = document.getElementById("previewAvatar");
                    preview.src = e.target.result;
                    preview.style.display = "block";
                };
                reader.readAsDataURL(file);
            }
        });
		$(document).ready(function () {
			CKEDITOR.replace('txtDetail', {
				customConfig: '/content/ckeditor/config.js',
				extraAllowedContent: 'span',
			});
		});
       
    </script>
}

ShopOnline/Areas/Admin/Views/AdminPages/Delete.cshtml
@model ShopOnline.Models.Page

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Page</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publish)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publish)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ordering)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ordering)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PageId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShopOnline/Areas/Admin/Views/AdminPages/Details.cshtml
@model ShopOnline.Models.Page

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h1>Chi tiết</h1>

<div>
    <h4>Page</h4>
    <hr />
    <div class="card shadow-sm p-4 bg-light">
        <h4 class="mb-3">@Model.PageName</h4>
        <dl class="row">
            <div class="col-md-4 mb-3">
                <img src="~/Images/Pages/@Model.Thumb" alt="@Model.PageName" class="img-fluid rounded border" style="max-height: 250px;" />
            </div>
            <div class="col-md-8">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.PageName)</th>
                            <td>@Html.DisplayFor(model => model.PageName)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Contents)</th>
                            <td>@Html.DisplayFor(model => model.Contents)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Publish)</th>
                            <td>@Html.DisplayFor(model => model.Publish)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Title)</th>
                            <td>@Html.DisplayFor(model => model.Title)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.MetaDesc)</th>
                            <td>@Html.DisplayFor(model => model.MetaDesc)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.MetaKey)</th>
                            <td>@Html.DisplayFor(model => model.MetaKey)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Alias)</th>
                            <td>@Html.DisplayFor(model => model.Alias)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.CreatedDate)</th>
                            <td>@Html.DisplayFor(model => model.CreatedDate)</td>
                        </tr>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Ordering)</th>
                            <td>@Html.DisplayFor(model => model.Ordering)</td>
                        </tr>
                    </tbody>
                </table>
            </div>

           
        </dl>
    </div>
   
</div>

<div class="mt-4 d-flex justify-content-between">
    <a asp-action="Index" class="btn btn-secondary">Quay lại danh sách</a>
    <a asp-action="Edit" asp-route-id="@Model.PageId" class="btn btn-primary">Chỉnh sửa</a>
</div>

ShopOnline/Areas/Admin/Views/AdminPages/Edit.cshtml
@model ShopOnline.Models.Page

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h1>Sửa</h1>

<h4>Page</h4>
<hr />
<div class="container mt-4">
    <div class="card shadow-sm rounded">
        <div class="card-header bg-info text-white">
            <h5 class="mb-0">Sửa tin tức</h5>
        </div>
		<div class="card-body">
			<form asp-action="Edit" enctype="multipart/form-data">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="PageId" />
				<div class="form-group">
					<label asp-for="PageName" class="control-label">Tên trang</label>
					<input asp-for="PageName" class="form-control" />
					<span asp-validation-for="PageName" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label for="exampleInputEmail1">Nội dung</label>
					@Html.TextAreaFor(x => x.Contents, new { @class = "form-control", @placeholder = "Nội dung", @id = "txtDetail" })
					@Html.ValidationMessageFor(x => x.Contents, null, new { @class = "text-danger" })
				</div>
				<div class="mb-3">
					<label class="form-label">Ảnh đại diện hiện tại</label><br />
					@if (!string.IsNullOrEmpty(Model.Thumb))
					{
						<img src="~/Images/Pages/@Model.Thumb" alt="Avatar" width="100" class="img-thumbnail mb-2" />
					}
				</div>
				<div class="form-group mb-3">
					<label asp-for="Thumb" class="form-label">Ảnh đại diện</label>
					<input type="file" name="Avatar" class="form-control" accept="image/*" />
					<img id="previewAvatar" class="img-thumbnail mt-2" style="display:none;" width="100" />
				</div>
				@Html.DropDownListFor(model => model.Publish,
									new List<SelectListItem>
				{
				new SelectListItem { Text = "Hoạt động", Value = "true" },
				new SelectListItem { Text = "Bị khóa", Value = "false" }
				},
									htmlAttributes: new { @class = "form-control" })
				<span asp-validation-for="Publish" class="text-danger small"></span>
				<div class="form-group">
					<label asp-for="Title" class="control-label"></label>
					<input asp-for="Title" class="form-control" />
					<span asp-validation-for="Title" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="MetaDesc" class="control-label"></label>
					<input asp-for="MetaDesc" class="form-control" />
					<span asp-validation-for="MetaDesc" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="MetaKey" class="control-label"></label>
					<input asp-for="MetaKey" class="form-control" />
					<span asp-validation-for="MetaKey" class="text-danger"></span>
				</div>
			
				<div class="form-group">
					<label asp-for="CreatedDate" class="control-label">Ngày tạo</label>
					<input asp-for="CreatedDate" class="form-control" />
					<span asp-validation-for="CreatedDate" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Ordering" class="control-label"></label>
					<input asp-for="Ordering" class="form-control" />
					<span asp-validation-for="Ordering" class="text-danger"></span>
				</div>
				<div class="form-group">
					<input type="submit" value="Lưu" class="btn btn-primary" />
				</div>
			</form>
		</div>
    </div>          
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary">Quay lại</a>
</div>
@section script {
	<script>
		document.querySelector('input[type="file"][name="Avatar"]').addEventListener('change', function (e) {
			const [file] = e.target.files;
			if (file) {
				const reader = new FileReader();
				reader.onload = function (e) {
					const preview = document.getElementById("previewAvatar");
					preview.src = e.target.result;
					preview.style.display = "block";
				};
				reader.readAsDataURL(file);
			}
		});
		$(document).ready(function () {
			CKEDITOR.replace('txtDetail', {
				customConfig: '/content/ckeditor/config.js',
				extraAllowedContent: 'span',
			});
		});
	</script>
}

ShopOnline/Areas/Admin/Views/AdminPages/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<ShopOnline.Models.Page>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h1>Quản lý Pages</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Thêm mới</a>
</p>





@using (Html.BeginForm("Index", "AdminPages", FormMethod.Get))
{
    <div class="input-group input-group-sm mb-3">
        @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Tìm tên " })
        <div class="input-group-append">
            <button type="submit" class="btn btn-info">Tìm</button>
        </div>
    </div>
}

 
    <table class="table table-bordered table-striped">
        <thead class="table-dark">
            <tr>
                <th>STT</th>
                <th>Tên</th>
                <th>Ảnh</th>                             
                <th>Title</th>
                <th>Alias</th>
				<th>Ngày tạo</th>
                <th>Công khai</th>
                <th>Thao tác</th>
            </tr>
        </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            var i = 1;
            @foreach (var item in Model)
            {
                <tr id="row_@item.PageId">
                    <td>@i</td>
                    <td>@item.PageName</td>                   
                    <td><img src="~/Images/Pages/@item.Thumb" width="60" height="60" class="img-thumbnail" /></td>
                    <td>@item.Title</td>
                    <td>@item.Alias</td>
                    <td>@item.CreatedDate</td>
                    <td>
                        @if (item.Publish == true)
                        {
                            <span class="badge bg-success">Hoạt động</span>
                        }
                        else
                        {
                            <span class="badge bg-danger">Bị khóa</span>
                        }
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.PageId" class="btn btn-sm btn-primary">Sửa</a>
                        <a asp-action="Details" asp-route-id="@item.PageId" class="btn btn-sm btn-info">Chi tiết</a>
                        <a data-id="@item.PageId" class="btn btn-sm btn-danger btnDelete">Xóa</a>
                    </td>
                </tr>
                i++;
            }
            }
        </tbody>
    </table>


<div class="d-flex justify-content-center mt-4">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }),
            new PagedListRenderOptions
    {
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        DisplayLinkToFirstPage = PagedListDisplayMode.Always,
        DisplayLinkToLastPage = PagedListDisplayMode.Always,
        Display = PagedListDisplayMode.IfNeeded,
        UlElementClasses = new[] { "pagination", "pagination-lg" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" }
    })
</div>
@section script {
    <script>
        $(document).ready(function () {
          $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                if (confirm("Bạn có chắc chắn muốn xóa tài khoản này?")) {

                    $.ajax({
                        url: '@Url.Action("Delete", "AdminPages")',
                        type: 'POST',
                        data: { id: id },
                        success: function (result) {
                            if (result.success) {
                                alert("Xóa tài khoản thành công!");
                                $("#row_"+id).remove();
                                location.reload();
                            } else {
                                alert("Xóa tài khoản thất bại: " + result.message);
                            }
                        },
                        error: function () {
                            alert("Đã xảy ra lỗi khi xóa tài khoản.");
                        }
                    });
                }
            });
        });
    </script>
}
<style>
    .pagination {
        margin-top: 20px;
    }

    .page-link {
        padding: 10px 18px;
        font-size: 12px;
    }

    .pagination .active .page-link {
        background-color: #007bff;
        border-color: #007bff;
        color: white;
    }
</style>